# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - bokeh
  - cartopy
  - contextily
  - dask
  - dask-labextension
  - datashader
  - descartes
  - distributed
  - fiona
  - folium
  - fsspec
  - gdal
  - geoalchemy2
  - geojson
  - geopandas
  - geoviews
  - gh
  - git
  - h5py
  - holoviews
  - hvplot
  - icepyx
  - ipyleaflet
  - ipympl
  - ipywidgets
  - ipython-sql
  - jupyter-book
  - jupyterhub-singleuser
  - jupyter-server-proxy
  - jupyterlab-git
  - jupyterlab=3
  - jupyter-resource-usage
  - kerchunk
  - matplotlib
  - nbgitpuller
  - numpy
  - pandas
  - panel
  - param>=1.11.1
  - pillow
  - pip
  - psycopg2
  - pycrs
  - pyproj
  - python_abi
  - python=3.8
  - rasterio
  - rioxarray
  - requests
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - tensorflow
  - zarr
